#!/usr/bin/env python3
"""copy the headers src/allhdrs.c pulls in to build/include, and write build/gen/tcc/consts.c
listing every `extern const T NAME;` in them, so tcc programs can link errno values and friends."""
import os, re, shutil, subprocess, sys
cosmo_inc, tcc, out_inc, out_c, libc_a, nm = sys.argv[1:7]
dep = "build/gen/tcc/allhdrs.d"
subprocess.run([tcc, "-w", "-nostdinc", "-I", cosmo_inc, "-include", "build/gen/tcc/predefs.h",
                "-include", f"{cosmo_inc}/libc/integral/normalize.inc", "-MD", "-MF", dep,
                "-c", "src/allhdrs.c", "-o", "build/gen/tcc/allhdrs.o"], check=True)
files = sorted({f for f in re.split(r"[\s\\]+", open(dep).read()) if f.startswith(cosmo_inc)})
shutil.rmtree(out_inc, ignore_errors=True)
for f in files:
    rel = os.path.relpath(f, cosmo_inc)
    os.makedirs(os.path.dirname(os.path.join(out_inc, rel)) or ".", exist_ok=True)
    shutil.copy(f, os.path.join(out_inc, rel))
shutil.copy("build/gen/tcc/predefs.h", os.path.join(out_inc, "jb_predefs.h"))
shutil.copy("src/jb_win.h", os.path.join(out_inc, "jb_win.h"))   # our Windows helpers, for the model
shutil.copy("src/jb.h", os.path.join(out_inc, "jb.h"))           # our helpers, for the model
shutil.rmtree("build/profile", ignore_errors=True); shutil.copytree("profile", "build/profile")   # per-section profile probes
shutil.rmtree("build/examples", ignore_errors=True); shutil.copytree("examples", "build/examples")
# names small models reach for that do not exist here. harmless ones redirect, foreign ones explain.
ALIAS = {"sys/sysconf.h": "unistd.h", "sys/unistd.h": "unistd.h", "sys/errno.h": "errno.h", "malloc.h": "stdlib.h",
         "memory.h": "string.h", "sys/dir.h": "dirent.h", "values.h": "limits.h", "sys/signal.h": "signal.h",
         "sys/fcntl.h": "fcntl.h", "sys/select.h": "poll.h", "sys/param.h": "limits.h", "strings.h": "string.h",
         "net/ifaddrs.h": "ifaddrs.h", "sys/ifaddrs.h": "ifaddrs.h", "sys/syslog.h": "syslog.h", "sys/utsname.h": "sys/utsname.h",
         "linux/limits.h": "limits.h", "sys/statfs.h": "sys/statvfs.h", "sys/vfs.h": "sys/statvfs.h", "sys/dirent.h": "dirent.h"}
FOREIGN = {"sys/sysctl.h": "no sysctl on this machine. use sysconf() from <unistd.h> or read files under /proc",
           "windows.h": "not Windows API. use POSIX calls", "mach/mach.h": "not macOS API. use POSIX calls",
           "sys/pstat.h": "use sysconf() or /proc", "kstat.h": "use /proc", "libproc.h": "use /proc",
           "linux/sysinfo.h": "use <sys/sysinfo.h>", "sys/cpuinfo.h": "read /proc/cpuinfo with fopen"}
for name, target in ALIAS.items():
    path = os.path.join(out_inc, name); os.makedirs(os.path.dirname(path), exist_ok=True)
    if not os.path.exists(path): open(path, "w").write(f"#include <{target}>\n")
for name, msg in FOREIGN.items():
    path = os.path.join(out_inc, name); os.makedirs(os.path.dirname(path), exist_ok=True)
    if not os.path.exists(path): open(path, "w").write(f"#error {msg}\n")
# a few constants are declared but never defined. keep only names libc.a really has.
defined = set()
for line in subprocess.run(["sh", nm, libc_a], capture_output=True, text=True).stdout.splitlines():
    parts = line.split()
    if len(parts) == 3 and parts[1] in "DdRrBbVv":
        defined.add(parts[2])
decl = re.compile(r"^extern const ([a-z_0-9]+)\s+([A-Za-z_0-9]+);", re.M)
consts, skipped = {}, []
for f in files:
    for typ, name in decl.findall(open(f, errors="replace").read()):
        (consts.__setitem__(name, typ) if name in defined else skipped.append(name))
if skipped: print("skipped, not in libc.a:", " ".join(sorted(set(skipped))))
with open(out_c, "w") as o:
    o.write("// generated by tools/hdrs.py. cosmo keeps errno values and other OS constants in variables.\n")
    o.write("// a tcc program that names ENOENT needs its address. no libc headers here, same reason as syms.c.\n")
    for name, typ in sorted(consts.items()):
        o.write(f"extern const char {name};\n")
    o.write("struct sym { const char *name; void *ptr; };\nconst struct sym jb_consts[] = {\n")
    for name in sorted(consts):
        o.write(f'  {{ "{name}", (void *)&{name} }},\n')
    o.write("  { 0, 0 } };\n")
print(f"{len(files)} headers, {len(consts)} constants")
